heat_template_version: 2016-10-14

description: >
  Úloha 8 – 1 VM s názvom odvodeným od názvu stacku a výstupom IP adresy.

parameters:
  network:
    type: string
    default: ext-net-154
  image:
    type: string
    default: cirros
  flavor:
    type: string
    default: 1c05r1d

resources:
  server:
    type: OS::Nova::Server
    properties:
      name: { str_replace: { template: "%stack%-server", params: { "%stack%": { get_param: "OS::stack_name" } } } }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: network }

outputs:
  server_ip:
    description: IPv4 adresa vytvorenej VM
    value: { get_attr: [ server, first_address ] }
